language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'
jobs:
  include:
  - stage: unit tests
    script:
       - 'echo "$TRAVIS_PULL_REQUEST"'
    script: 
       - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test --coverage; fi'
       - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test; fi'

