language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

jobs:
  include:
    - stage: lint
      script:
       - yarn lint
      if: branch = master
jobs:
  include: 
  - stage: unit tests
    script:
       - 'echo "$TRAVIS_PULL_REQUEST"'
    script: 
       - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test --coverage; fi'
       - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test; fi'
  - if: branch = master
    
     
before_script:
	  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  export PLATFORM=osx$OSX-x86_64-clang`clang -dumpversion`; fi
	  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash gcc; brew link --overwrite gcc; gfortran --version; fi
	  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PLATFORM=linux-x86_64-gcc`gcc -dumpversion`; fi
	  - git clone https://github.com/coin-or-tools/BuildTools
    - bash BuildTools/get.dependencies.sh fetch > /dev/null
