language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

stages:
  - test 
  - test-coverage 

 
jobs:
  include:
  - stage: test-coverage
    script:
       - yarn test --coverage
    if: type branch IN(master)

jobs:
  include: 
  - stage: test
    script:
       - yarn test       