language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'
jobs:
  include:
  - stage: unit tests
    script: 
       - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; echo "$TRAVIS_PULL_REQUEST"; fi'
       - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test; fi'

