language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

env:
  - FOO=foo
  - FOO=bar
  
script: echo $FOO


stages:
  - test 
  - test-coverage 
 
jobs:
  include:
  - stage: test-coverage
    script:
       - yarn test --coverage
  - stage: test
    script:
       - yarn test
  - stage: deploy
      script: echo Deploy
                 