language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'
jobs:
  include:
  - stage: unit tests
    script: 
      - |
        if [ "${PULL_REQUEST}" == "false" ]; then
          yarn test-coverage;
        else
           yarn test;  
        fi
 