language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

stages:
  - name: test 
    if: type = pull_request
  - name: test-coverage 
    if: type NOT IN(pull_request)
 
 
jobs:
  include: 
  - stage: test
    script:
       - yarn test
 
jobs:
  include:
  - stage: test-coverage
    script:
       - yarn test --coverage
    
       