language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

jobs:
  include:
    - stage: lint
      script:
       - yarn lint
      if: branch = master
jobs:
  include: 
  - stage: unit tests
    script:
       - 'echo "$TRAVIS_PULL_REQUEST"'
    script: 
       - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn test --coverage; fi'
       - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn test; fi'
  - if: branch = master
    
     
before_script:
  - if [ $TRAVIS_PULL_REQUEST == 'true' ];
    then yarn  test;
    else yarn test --coverage;
    fi
