language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

jobs:
  include:
    - stage: lint
      script:
       - yarn lint
      if: branch = master
jobs:
  include: 
  - stage: unit tests
    script:
       - 'echo "$TRAVIS_PULL_REQUEST"'
    script: 
       -  if [ $TRAVIS_PULL_REQUEST == 'true' ];
          then yarn  test;
          else make unittests;
          fi
  