language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

env:
  - FOO=foo
  - FOO=bar
  
script: echo $FOO


stages:
  - test 
  - name: coverage
    if: branch = master
  
jobs:
  include:
  - stage: coverage
    script:
       - echo coverage
  - stage: test
    script:
       - yarn test
  
                 