language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'

stages:
  - lint
  - name: test
    if: type = pull_request 
  - name: test-with-coverage 
    if: (NOT (type = pull_request ))
  - deploy  
    

jobs:
  include:
  - stage: lint
    script:
      - yarn run build-css
      - yarn lint
  - stage: test-with-coverage 
    script: yarn test-coverage
  - stage: test 
    script: yarn test

