language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'


stages:
  - test 
  - name: coverage
    if: (NOT (type = pull_request ))
  
jobs:
  include:
  - stage: coverage
    script:
       - echo coverage
  - stage: test
    script:
       - yarn test
  
                 